spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=neoris
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080
  servlet:
    context-path: /api/v1

